"""Workspace membership: product (default), aux, and bom.

Roles are declared in each repo's ``gitconvoy.toml`` (``role = "aux"|"bom"``).
``git convoy init`` writes local ``.gitconvoy/aux.toml``. Without that file,
BOM falls back to ``*-bom`` ids; unmarked repos are product.
"""

from __future__ import annotations

from pathlib import Path

from gitconvoy.errors import GitConvoyError
from gitconvoy.state import STATE_DIRNAME

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None  # type: ignore[assignment]

AUX_FILENAME = "aux.toml"
VALID_ROLES = frozenset({"product", "aux", "bom"})


def aux_toml_path(workspace: Path) -> Path:
    return workspace / STATE_DIRNAME / AUX_FILENAME


def read_repo_role(repo_path: Path) -> str:
    """Return role from repo-root gitconvoy.toml, else product."""
    for name in ("gitconvoy.toml", ".gitconvoy.toml"):
        path = repo_path / name
        if not path.is_file():
            continue
        data = _load_toml(path)
        role = str(data.get("role") or "product").strip().lower()
        if role not in VALID_ROLES:
            raise GitConvoyError(
                f"{path}: invalid role {role!r} (expected product|aux|bom)"
            )
        return role
    return "product"


def load_membership(workspace: Path) -> dict[str, list[str]]:
    """Load local aux.toml. Missing file → empty aux, empty bom (caller applies *-bom fallback)."""
    path = aux_toml_path(workspace)
    if not path.is_file():
        return {"aux": [], "bom": []}
    data = _load_toml(path)
    aux = _string_list((data.get("aux") or {}).get("repos") if isinstance(data.get("aux"), dict) else None)
    bom = _string_list((data.get("bom") or {}).get("repos") if isinstance(data.get("bom"), dict) else None)
    return {"aux": aux, "bom": bom}


def write_membership(workspace: Path, *, aux: list[str], bom: list[str]) -> Path:
    path = aux_toml_path(workspace)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Local git-convoy membership (not versioned with the workspace).",
        "# Regenerated by: git convoy init",
        "# Default: every discovered repo is product. Listed repos are exceptions.",
        "",
        "[aux]",
        "repos = [",
    ]
    for repo_id in aux:
        lines.append(f'  "{repo_id}",')
    lines.extend(
        [
            "]",
            "",
            "[bom]",
            "repos = [",
        ]
    )
    for repo_id in bom:
        lines.append(f'  "{repo_id}",')
    lines.extend(["]", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def refresh_membership(workspace: Path, repos: list) -> dict:
    """Scan repo markers and rewrite aux.toml. ``repos`` are workspace.Repo-like."""
    aux: list[str] = []
    bom: list[str] = []
    scanned: list[dict] = []
    for repo in repos:
        role = read_repo_role(repo.path)
        scanned.append({"id": repo.id, "path": repo.rel, "role": role})
        if role == "aux":
            aux.append(repo.id)
        elif role == "bom":
            bom.append(repo.id)
    aux = sorted(set(aux))
    bom = sorted(set(bom))
    path = write_membership(workspace, aux=aux, bom=bom)
    return {
        "ok": True,
        "path": str(path),
        "aux": aux,
        "bom": bom,
        "repos": scanned,
    }


def is_aux_id(workspace: Path, repo_id: str) -> bool:
    return repo_id in set(load_membership(workspace)["aux"])


def is_bom_id(workspace: Path, repo_id: str) -> bool:
    membership = load_membership(workspace)
    if membership["bom"]:
        return repo_id in set(membership["bom"])
    return repo_id.endswith("-bom")


def _string_list(raw: object) -> list[str]:
    if raw is None:
        return []
    if not isinstance(raw, list):
        raise GitConvoyError("aux.toml: repos must be a list of strings")
    out: list[str] = []
    for item in raw:
        text = str(item or "").strip()
        if not text:
            continue
        # Allow path form ops/foo → id foo
        if "/" in text:
            text = text.rstrip("/").split("/")[-1]
        out.append(text)
    return out


def _load_toml(path: Path) -> dict:
    if tomllib is None:
        raise GitConvoyError("tomllib is required (Python 3.11+)")
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        raise GitConvoyError(f"invalid TOML {path}: {exc}") from exc
